import fs from 'node:fs';
import vm from 'node:vm';
const c={window:{}};vm.createContext(c);vm.runInContext(fs.readFileSync('data/photos.js','utf8'),c);
const photos=c.window.MADAGASCAR_PHOTOS;
const alts={'allee-baobabs':'Les grands baobabs de l’allée près de Morondava','andringitra':'Reliefs de l’Andringitra derrière les maisons et les champs','ile-aux-nattes':'Eau peu profonde et végétation littorale de l’Île aux Nattes','isalo':'Vallée rocheuse et reliefs de grès de l’Isalo','masoala':'Rivage ombragé et racines des arbres à Masoala','mer-emeraude':'Bateaux sur les eaux turquoise de la Mer d’Émeraude près de Ramena','nosy-iranja':'Plage de Nosy Iranja bordée de palmiers et de pirogues','nosy-tanikely':'Nudibranche Phyllidiella pustulosa observé à Nosy Tanikely','ranomafana':'Passerelle près de la forêt de Ranomafana','tsaranoro':'Paroi granitique de Karambony dans la vallée de Tsaranoro','tsingy-bemaraha':'Passerelle entre les reliefs calcaires des Tsingy de Bemaraha','tsingy-rouges':'Formations d’érosion ocre des Tsingy Rouges'};
for(const [id,p] of Object.entries(photos)){p.alt=alts[id];if(p.author==='Diego Delso')p.author='Diego Delso, delso.photo';}
fs.writeFileSync('data/photos.js','window.MADAGASCAR_PHOTOS = '+JSON.stringify(photos,null,2)+';\n');
let credits=fs.readFileSync('CREDITS.md','utf8');const start=credits.indexOf('## Image de couverture');const end=credits.indexOf('## Code tiers');
credits=credits.slice(0,start)+'## Photographies\n\nMétadonnées de licence consultées sur Wikimedia Commons le 17 septembre 2026. Images hébergées dans `assets/photos/`, redimensionnées et compressées en JPEG, avec recadrage visuel selon le format d’écran. Chaque image et ses adaptations restent sous la licence indiquée. La licence MIT du code ne couvre pas ces photographies.\n\n'+Object.entries(photos).map(([id,p])=>'### '+alts[id]+'\n\n- Fichier local : `'+p.src+'`\n- Original : ['+p.title+']('+p.source+')\n- Auteur : '+p.author+'\n- Licence : ['+p.license+']('+p.licenseUrl+')\n').join('\n')+'\n'+credits.slice(end);
credits+='\n## Sélection de découverte\n\nLes douze coups de cœur constituent une sélection éditoriale, sans classement objectif. Les durées proposées sont des suggestions de séjour sur place, hors transferts. Les descriptions prolongent les fiches du projet et les repères de l’[Office national du tourisme](https://madagascar-tourisme.com/wp-content/uploads/2025/04/Carte-touristique-Madagascar.pdf). Le parcours de Bemaraha s’appuie sur la [présentation du parc par l’office du tourisme](https://madagascar-tourisme.com/fr/la-destination/le-nord-ouest/tsingy-de-bemaraha/).\n';fs.writeFileSync('CREDITS.md',credits);
let css=fs.readFileSync('assets/styles.css','utf8').replace("'top':12px",'top:12px').replace('https://upload.wikimedia.org/wikipedia/commons/b/bb/Baobab_Avenue_1.JPG','photos/allee-baobabs.jpg');fs.writeFileSync('assets/styles.css',css);
fs.appendFileSync('README.md','\n## Découverte photographique\n\nDouze destinations mises en avant avant la carte, filtrables par paysages, îles, randonnées et forêts. Les photos sont locales et leurs crédits sont affichés sous les images ainsi que dans la section photographique. `data/photos.js` conserve les sources, auteurs, licences et modifications. `data/discoveries.js` contient les textes et suggestions de séjour. Les rubriques Développement et Opportunités sont annoncées pour une prochaine étape.\n\nPrévisualisation locale : `node scripts/preview.cjs`, puis http://127.0.0.1:8000.\n');
